
default: &default
  host_url: http://192.168.99.1:3000
  min_cron_interval: <%= 10.minutes %>

development:
  <<: *default
  min_cron_interval: <%= 1.minutes %>

test:
  <<: *default
 
production:
  <<: *default
  host_url: http://cron.only-x.com

